# Generated by Django 4.1.13 on 2024-08-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=200, verbose_name='ادرس سایت')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره تلفن')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ادرس ایمیل')),
                ('copy_rights', models.TextField(verbose_name='متن کپی رایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
