# Generated by Django 4.1.13 on 2024-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_sitesetting_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس'),
        ),
    ]
