# Generated by Django 4.1.13 on 2024-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_module', '0002_alter_contact_us_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کامل'),
        ),
    ]
