# Generated by Django 4.1.13 on 2024-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_module', '0003_alter_contact_us_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='is_read_by_admin',
            field=models.BooleanField(null=True, verbose_name='خوانده شده توسط ادمین'),
        ),
    ]
