# Generated by Django 4.1.13 on 2024-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_module', '0007_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
