# Generated by Django 4.1.13 on 2024-07-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_module', '0008_alter_profile_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
