# Generated by Django 4.1.13 on 2024-08-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=400, verbose_name='عنوان در url')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('selected_categories', models.ManyToManyField(to='article_module.article_category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
