# Generated by Django 4.1.13 on 2024-08-10 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_module', '0005_article_list_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_list',
            name='create_module',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 8, 10), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_list',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام نویسنده'),
        ),
    ]
